var data = {
    chill: {
        title: "Chill一下满血复活",
        card: [
            {
                chillId: 1,
                title: "Lofi Girl - Christmas 2023",
                subtitle: "Various Artists/Lofi Girl",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001MN7wZ4WEomp_1.jpg",
                hrefUrl: "",
            },
            {
                chillId: 2,
                title: "Lazy Sunday",
                subtitle: "Various Artists/Lofi Girl",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001vvIvQ1n1Y27_3.jpg",
                hrefUrl: "",
            },
            {
                chillId: 3,
                title: "18 MILES",
                subtitle: "Keyoung Fresh/CHILLVIBE 丘稗/眠",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001tPsgq011sE1_1.jpg",
                hrefUrl: "",
            },
            {
                chillId: 4,
                title: "Love is something",
                subtitle: "Keyoung Fresh",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001P3qQ12xRz6S_1.jpg",
                hrefUrl: "",
            },
            {
                chillId: 5,
                title: "青 韵",
                subtitle: "CureGirl治愈学姐",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000002Q3Wta2VRNf8_1.jpg",
                hrefUrl: "",
            },
            {
                chillId: 6,
                title: "Bluewerks Vol. 11: Behind The Walls",
                subtitle: "Bluewerks/goosetaf",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000002i3RwF3w2iNV_1.jpg",
                hrefUrl: "",
            },
        ],
    },
    christmas: {
        title: "圣诞节氛围感BGM",
        card: [
            {
                christmasId: 1,
                title: "Am Kaminknistern",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001MN7wZ4WEomp_1.jpg",
                singername: "Kainbeats",
                albumname: "Lofi Girl - Christmas 2023",
                hrefUrl: "",
            },
            {
                christmasId: 2,
                title: "Christmas by the Fireplace",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001Rp82o175Uhj_1.jpg",
                singername: "Sleepy Tom",
                albumname: "Christmas Lofi",
                hrefUrl: "",
            },
            {
                christmasId: 3,
                title: "Waiting By The Fireplace",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001MN7wZ4WEomp_1.jpg",
                singername: "Thaehan",
                albumname: "Lofi Girl - Christmas 2023",
                hrefUrl: "",
            },
            {
                christmasId: 4,
                title: "That Time Of The Year",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001MN7wZ4WEomp_1.jpg",
                singername: "No Spirit",
                albumname: "Lofi Girl - Christmas 2023",
                hrefUrl: "",
            },
            {
                christmasId: 5,
                title: "Christmas",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M0000027Wpml0L2aS9_1.jpg",
                singername: "LoFi Waiter",
                albumname: "Lofi Christmas",
                hrefUrl: "",
            },
            {
                christmasId: 6,
                title: "Mistletoe Wonder",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001MN7wZ4WEomp_1.jpg",
                singername: "Lucid Keys",
                albumname: "Lofi Girl - Christmas 2023",
                hrefUrl: "",
            },
            {
                christmasId: 7,
                title: "Snowballs",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001MN7wZ4WEomp_1.jpg",
                singername: "xander./Lucid Keys",
                albumname: "Lofi Girl - Christmas 2023",
                hrefUrl: "",
            },
            {
                christmasId: 8,
                title: "White Christmas",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000002X5QrF4QBqdZ_1.jpg",
                singername: "Bflynn",
                albumname: "Hbdj: A Lofi Christmas",
                hrefUrl: "",
            },
            {
                christmasId: 9,
                title: "Letter To Santa",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001MN7wZ4WEomp_1.jpg",
                singername: "Thaehan",
                albumname: "Lofi Girl - Christmas 2023",
                hrefUrl: "",
            },
        ],
    },
    dopamine: {
        title: "多巴胺蒸汽波发射ing",
        card: [
            {
                dopamineId: 1,
                title: "脱离现实 | 蒸汽波纯音乐",
                cover: "http://qpic.y.qq.com/music_cover/UYaunx856XZrhEh6IpyK6orQ26xtUPddaRLibvKMCzZnprOloAUAJPA/300?n=1",
                playNumber: 991599,
                hrefUrl: "",
            },
            {
                dopamineId: 2,
                title: "今 天 要 再 蒸 汽 一 點 喲",
                cover: "http://qpic.y.qq.com/music_cover/dqA75cm8geDw9KI3sHeib5y3iakiceFo3P45glkGtwiaf3wyPxhWWJhIcw/300?n=1",
                playNumber: 31628,
                hrefUrl: "",
            },
            {
                dopamineId: 3,
                title: "复古蒸汽波 | 奉上迷醉轻柔心情",
                cover: "http://qpic.y.qq.com/music_cover/pp7r6cyIIR5wicUkXH8ibwWSCQ80CXCZibhERicclM9CcCwM8bedgLyz1w/300?n=1",
                playNumber: 149816,
                hrefUrl: "",
            },
            {
                dopamineId: 4,
                title: "蒸汽波»月色“迷幻気”带走烦恼",
                cover: "http://qpic.y.qq.com/music_cover/qA5OZ2Jr0rJeuhZljBkn0rYLz41LwjgIPCgQBahianFe2GraDI0J3Rw/300?n=1",
                playNumber: 12093,
                hrefUrl: "",
            },
            {
                dopamineId: 5,
                title: "浴室蒸汽波：情迷少女浪漫氛围感",
                cover: "http://qpic.y.qq.com/music_cover/qySHBaLckrOIYib7GXCWmDbG7K4GRBmyC4iaDcxJu3S8dfk38EY79przq6zaF1ibGTv/300?n=1",
                playNumber: 220411,
                hrefUrl: "",
            },
            {
                dopamineId: 6,
                title: "水汽弥漫入耳 • 迷醉蒸汽波",
                cover: "http://qpic.y.qq.com/music_cover/JwclnudaObJXGgJOkTPBGcZkia3nQbicQYtSJKCy4f9K1JMNkQZMLv4A/300?n=1",
                playNumber: 559839,
                hrefUrl: "",
            },
        ],
    },
    checking: {
        title: "每日打卡体验沉浸式陪伴",
        card: [
            {
                checkingId: 1,
                title: "解锁冬日圣诞旋律，和Lofi Girl一起学习",
                cover: "http://img.tencentmusic.com/T002R1080x1920M000001p0jDx3Q8fDC.jpeg?imageView2/4/w/500/h/500",
                playNumber: 83199,
                hrefUrl: "",
            },
            {
                checkingId: 2,
                title: "舒缓焦躁放松神经随着音符坠入梦乡",
                cover: "http://img.tencentmusic.com/T002R1080x1920M000001Snuxi22MBuz.jpeg?imageView2/4/w/500/h/500",
                playNumber: 48114,
                hrefUrl: "",
            },
            {
                checkingId: 3,
                title: "舒缓的微风，与Lofi Girl静坐冥想",
                cover: "http://img.tencentmusic.com/T002R1080x1920M0000039rLLj1x9hts.jpeg?imageView2/4/w/500/h/500",
                playNumber: 36659,
                hrefUrl: "",
            },
            {
                checkingId: 4,
                title: "聆听入境，在梦中与森林共呼吸",
                cover: "http://img.tencentmusic.com/T002R1080x1920M000001SEFgu2X6r4w.jpeg?imageView2/4/w/500/h/500",
                playNumber: 67099,
                hrefUrl: "",
            },
            {
                checkingId: 5,
                title: "与Lofi Girl邂逅午后学习时光",
                cover: "http://img.tencentmusic.com/T002R1080x1920M0000034qyov3NglhK.jpeg?imageView2/4/w/500/h/500",
                playNumber: 35647,
                hrefUrl: "",
            },
            {
                checkingId: 6,
                title: "冥想调息，呼吸间感受精神流动",
                cover: "http://img.tencentmusic.com/T002R1080x1920M000003Zvx9Z3bMQAO.jpeg?imageView2/4/w/500/h/500",
                playNumber: 53125,
                hrefUrl: "",
            },
        ],
    },
    relax: {
        title: "学习工作也可以很松弛",
        card: [
            {
                relaxId: 1,
                title: "【Lofi Girl】陪伴温暖圣诞节",
                cover: "http://qpic.y.qq.com/music_cover/U1KMglFEuN5fUO6dLwsiaZSvOhMxPTdfCpXiciaGmZR6GdibibgTEicP3umuyjdjvb6Twj/300?n=1",
                playNumber: 514643,
                hrefUrl: "",
            },
            {
                relaxId: 2,
                title: "【Lofi Boy】工作游戏通关buff",
                cover: "http://qpic.y.qq.com/music_cover/U1KMglFEuN5fUO6dLwsiaZSvOhMxPTdfCQMH411PyEpiaLe6YO2tU8HZfbVtxWfxKk/300?n=1",
                playNumber: 70178,
                hrefUrl: "",
            },
            {
                relaxId: 3,
                title: "Lofi Hiphop：沉浸式惬意学习",
                cover: "http://qpic.y.qq.com/music_cover/jxOgJv0aSm7ia337iaLwq3xbIWcRkof4UewWyxEtLYDLG6qfYIM68rlA/300?n=1",
                playNumber: 335566,
                hrefUrl: "",
            },
            {
                relaxId: 4,
                title: "【Lofi Girl】专注高效办公",
                cover: "http://qpic.y.qq.com/music_cover/U1KMglFEuN5fUO6dLwsiaZSvOhMxPTdfCbgibUvNbYbRAE4mP26N3WGbn7cq8ickjEo/300?n=1",
                playNumber: 278152,
                hrefUrl: "",
            },
            {
                relaxId: 5,
                title: "【Lofi Boy】通勤驾驶必备BGM",
                cover: "http://qpic.y.qq.com/music_cover/U1KMglFEuN5fUO6dLwsiaZSvOhMxPTdfCQMH411PyEphvpjKtM9ic0YicZZHm0hCOp9/300?n=1",
                playNumber: 55855,
                hrefUrl: "",
            },
            {
                relaxId: 6,
                title: "【Lofi Girl】冥想|放松|治愈",
                cover: "http://qpic.y.qq.com/music_cover/U1KMglFEuN5fUO6dLwsiaZSvOhMxPTdfCHErH8oibYGDCj9DKL19Lzic5IzNWqibb3Cq/300?n=1",
                playNumber: 279360,
                hrefUrl: "",
            },
        ],
    },
    hiphop: {
        title: "当Hip-Hop遇见Jazz",
        card: [
            {
                hiphopId: 1,
                title: "Samurai champloo music record masta",
                subtitle: "TSUTCHIE/Force of Nature",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000003ha5CL0vbF0b_1.jpg",
                hrefUrl: "",
            },
            {
                hiphopId: 2,
                title: "Melancholy Nights",
                subtitle: "Nujabes",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000004Mrpi41gCb8k_1.jpg",
                hrefUrl: "",
            },
            {
                hiphopId: 3,
                title: "High Noon",
                subtitle: "DJ OKAWARI",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000002A44To1QgnEb_1.jpg",
                hrefUrl: "",
            },
            {
                hiphopId: 4,
                title: "Lonely",
                subtitle: "iwamizu",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001WgyiA1jLavg_1.jpg",
                hrefUrl: "",
            },
            {
                hiphopId: 5,
                title: "Rugged Mystic Jazz",
                subtitle: "西原健一郎",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000000Qv5O00hIyHS_1.jpg",
                hrefUrl: "",
            },
            {
                hiphopId: 6,
                title: "就是玩儿",
                subtitle: "Jiaming/Alienkey",
                cover: "https://y.gtimg.cn/music/photo_new/T002R300x300M000001sSpca0fGOFQ_1.jpg",
                hrefUrl: "",
            },
        ],
    },
    sleep: {
        title: "深度放松伴你入眠",
        card: [
            {
                sleepId: 1,
                title: "【Lofi Girl】睡前助眠放松",
                cover: "http://qpic.y.qq.com/music_cover/U1KMglFEuN5fUO6dLwsiaZSvOhMxPTdfCHib4MKWYvC1wSAQ0BibWdgF9vovuCZJWgg/300?n=1",
                cnt: 192103,
                hrefUrl: "",
            },
            {
                sleepId: 2,
                title: "Lofi舒憩舱☾深度沉眠chill地带",
                cover: "http://qpic.y.qq.com/music_cover/VgJ9yB2pf097libEdIw2frkZ7DS9ZeArwibRQbrKyCqxWtIDxjqnFv2g/300?n=1",
                cnt: 22206,
                hrefUrl: "",
            },
            {
                sleepId: 3,
                title: "Lo-fi摇篮曲✨跌入夜氛围佳境",
                cover: "http://qpic.y.qq.com/music_cover/ClOO08libib30HrDic0JlEwKsY4ic5lr3Ke9GicaBXK3UwSEPwHdwUaDkKQ/300?n=1",
                cnt: 49547,
                hrefUrl: "",
            },
            {
                sleepId: 4,
                title: "迷醉lofi：枕边的午夜臆想症",
                cover: "http://qpic.y.qq.com/music_cover/8us3IjqPib6Aficmrq3AXWiaI2CTMDzUqdGSCHAS6EiaZnRbTlENr52F8Q/300?n=1",
                cnt: 35258,
                hrefUrl: "",
            },
            {
                sleepId: 5,
                title: "Lo-Fi助眠剂｜一副音药就见效",
                cover: "http://qpic.y.qq.com/music_cover/bp55dcibXqUjaQjwt6gP1ia4SicYBAWPFHsnHojCIygiaJibNa88Z3Z6yFg/300?n=1",
                cnt: 58107,
                hrefUrl: "",
            },
            {
                sleepId: 6,
                title: "助眠Lofi：舒缓节拍击碎失眠因子",
                cover: "http://qpic.y.qq.com/music_cover/7rwpibGibr1ibJjia8cQpOUHaNHZsk6Y1fAAu5a8Yll9B8CHic5NabxQxdg/300?n=1",
                cnt: 30710,
                hrefUrl: "",
            },
        ],
    },
    atmosphere: {
        title: "氛围制造专家",
        card: [
            {
                atmosphereId: 1,
                title: "Lofi Girl",
                cover: "http://y.gtimg.cn/music/photo_new/T001R150x150M0000003z13h1mrxyF_7.jpg",
                hrefUrl: "",
            },
            {
                atmosphereId: 2,
                title: "眠",
                cover: "http://y.gtimg.cn/music/photo_new/T001R150x150M000001bRnIy0hr7YT_5.jpg",
                hrefUrl: "",
            },
            {
                atmosphereId: 3,
                title: "Keyoung Fresh",
                cover: "http://y.gtimg.cn/music/photo_new/T001R150x150M00000347KwV0Kz2Zv_9.jpg",
                hrefUrl: "",
            },
            {
                atmosphereId: 4,
                title: "CureGirl治愈学姐",
                cover: "http://y.gtimg.cn/music/photo_new/T001R150x150M000003ACT1v0B32TQ_2.jpg",
                hrefUrl: "",
            },
            {
                atmosphereId: 5,
                title: "elijah who",
                cover: "http://y.gtimg.cn/music/photo_new/T001R150x150M000001jTei803h5NM_2.jpg",
                hrefUrl: "",
            },
            {
                atmosphereId: 6,
                title: "In Love With a Ghost",
                cover: "http://y.gtimg.cn/music/photo_new/T001R150x150M000003J8bkg1P9X1V_2.jpg",
                hrefUrl: "",
            },
            {
                atmosphereId: 7,
                title: "Kijugo",
                cover: "http://y.gtimg.cn/music/photo_new/T001R150x150M000001PukRx3yZf1I_2.jpg",
                hrefUrl: "",
            },
        ],
    },
    comments: {
        item: [
            {
                commentId: 1,
                commentTime: "2023-09-27 17:37",
                username: "场景任意门",
                cover: "https://pic6.y.qq.com/qqmusic/avatar/6f7745356f7736694e6534736f632a2a-1673945651/140",
                vipLevel: 7,
                commentText: "lofi girl终于有了，之前就很喜欢在优tube上听，这下终于不用翻来翻去的了。😂",
                location: "福建",
                like: 5,
                hasSubComment: 1,
                subComment: [
                    {
                        subId: 1,
                        subUser: "无然而已",
                        subText: "人的倒数第二edff",
                    },
                    {
                        subId: 2,
                        subUser: "王宽",
                        subText: "gwbt",
                    },
                ],
            },
            {
                commentId: 2,
                commentTime: "2023-10-18 10:19",
                username: "mojo",
                cover: "https://thirdqq.qlogo.cn/g?b=sdk&k=LcOYJia0sD7HT8endZW0ZIQ&s=140&t=1556660164",
                vipLevel: 0,
                commentText: "十一到处人挤人，宅家里还好有这些Chill的音乐，高级氛围感拉满了！",
                location: "北京",
                like: 19,
                hasSubComment: 0,
                subComment: [],
            },
            {
                commentId: 3,
                commentTime: "2024-02-09 08:45",
                username: "...T",
                cover: "https://thirdqq.qlogo.cn/g?b=sdk&k=8N2K6bxnN6VNSYzYiauNRrA&kti=ZioITAAAAAE&s=140&t=1712835932",
                vipLevel: 4,
                commentText: "我已经上班了三天，所以请不要对我说假期余额不足",
                location: "辽宁",
                like: 10,
                hasSubComment: 1,
                subComment: [
                    {
                        subId: 1,
                        subUser: "xiao",
                        subText: "哈哈哈哈哈",
                    },
                ],
            },
        ],
    },
};
